### ISSUE TITLE
[FEATURE] Support for Thanos >= v0.13.0

### ISSUE THREAD

**Issue by malyem** [syberalexis/puppet-thanos#25]
In Thanos version v0.13.0 invocation for `thanos bucket web` has been changed https://github.com/thanos-io/thanos/pull/2513.
Valid execution should be `thanos tools bucket web`.
We have at least two options to fix it in Puppet:
1. Add `tools` in https://github.com/syberalexis/puppet-thanos/blob/master/manifests/bucket_web.pp#L71 
2. Refactor all files and invocations to keep naming convention, for example `manifests/bucket_web.pp` should be `manifests/bucket_tools_web.pp`...

**Comment by syberalexis** [comment]
I have already start to support Thanos version 0.14.0.
I will do some changes to support version 0.15.0 and test it before pull it ;)

**Comment by syberalexis** [comment]
Fixed and deployed in version 1.1.0
