### ISSUE TITLE
[FEATURE] Support for Thanos >= v0.16.0

### ISSUE THREAD

**Issue by Chr0my** [syberalexis/puppet-thanos#30]
Starting to v0.16.0, a breaking change has been introduced related to query-frontend `log_queries_longer_than` which has been renamed to `log-queries-longer-than` (https://github.com/thanos-io/thanos/pull/3114)
[Here's](https://github.com/syberalexis/puppet-thanos/pull/29) the pull request to fix it, if you can take some time to check it / merge it 🙏 (apparently the tests fails due to timeout...)

**Comment by syberalexis** [comment]
Deployed by #29
