### ISSUE TITLE
[FEATURE] Support for Thanos >= v0.26.0

### ISSUE THREAD

**Issue by Chr0my** [syberalexis/puppet-thanos#31]
Hi, 

Would it be possible to add support for Thanos v0.26.0? 

For instance, manifests/sidecar.pp has now 2 flags that are not supported and prevent the process to start:

- `receive.connection-pool-size`

- `receive.connection-pool-size-per-host`

Rename `stores` to `endpoints` for the querier as `store` is now deprecated

Also, it would be great to allow the module increasing the number of file descriptor the process can open (1024 by default)(https://thanos.io/tip/operating/binary-index-header.md/#impact-on-number-of-open-file-descriptors)

**Comment by syberalexis** [comment]
Version 1.3.0 is now deployed on Puppet Forge ;)
