### ISSUE TITLE
[FEATURE] Support latest version of puppet-archive in dependency

### ISSUE THREAD

**Issue by ttousai** [syberalexis/puppet-thanos#39]
**Is your feature request related to a problem? Please describe.**
I am running version 6.1.0 of puppet-archive and puppet-thanos fails because it supports up to version 5.0.0.
The version of puppet-archive as of this writing is v6.1.1.

**Describe the solution you'd like**
Add support for puppet-archive to include v6.1.1.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by syberalexis** [comment]
Hello. thank you to contribute to this project :)

Fixed in #40
Released in v1.5.0 and deployed
