### ISSUE TITLE
[BUG] Release 1.6.0 missing on Puppet Forge

### ISSUE THREAD

**Issue by roock** [syberalexis/puppet-thanos#51]
**Describe the bug**
Release 1.6.0 is not available on Puppet Force

**To Reproduce**
https://forge.puppet.com/modules?limit=25&sort_by=rank&module_groups=base%20pe_only&q=thanos

<img width="918" alt="image" src="https://github.com/syberalexis/puppet-thanos/assets/533172/8d190d57-2995-43fa-b73a-65016643c476">

**Expected behavior**
All releases should be present on Puppet Forge.

**Environment**
N/A

**Comment by syberalexis** [comment]
Hello,

Thank you and sorry for that bug.
I will change the CI to have one more stable.
I mannually publish the release now.

Have a nice day.
